name: CI

on: [push, pull_request]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: debug
        uses: actions/github-script@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const { promisify } = require('util');

            const files = await promisify(fs.readdir)('.');
            console.log(files);

            const { commits, head_commit } = context.payload;
            console.log({ context, head_commit });
            for (const commit of commits) {
              console.log(commit);
            }

            const [, base, head] = context.payload.compare.match(/\/compare\/([0-9a-f]+)\.\.\.([0-9a-f]+)$/);
            if (base && head) {
              const { owner, repo } = context.repo;
              const diffs = await github.repos.compareCommits({ owner, repo, base, head });
              console.log({ diffs });
            }
