name: CI

on: [push, pull_request]

jobs:
  debug:
    - name: debug
      uses: actions/github-script@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs');
          const { promisify } = require('util');

          const files = await promisify(fs.readdir)('.');
          console.log(files);

          console.log({ github, context });
